### ISSUE TITLE
The git plugin

### ISSUE THREAD

**Issue by halink0803** [weirdpattern/hyper-ayu-mirage#4]
I saw in your screenshot there is a git plugin showing the branch and changes on the right of directory,  which plugin do you use to have that? I install hyper-ayu-mirage theme on my hyper but it does not show up.

Thank you so much 👍

**Comment by weirdpattern** [comment]
hey @halink0803, is not really a plugin that I'm using.
Is part of my bash profile (*nix systems) and powershell profile (windows systems).
You can get the code from my [dotfiles](https://github.com/weirdpattern/dotfiles). 

Hope this helps!

**Comment by halink0803** [comment]
Thank you so much for your answer 👍
